### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by tucq88** [gsmartsolutions/pet-timesheet#3]
We don't have final decision about Tech stack yet. 
But I supposed to use `Laravel as Backend` and building an `single page application` to consume APIs, We could use `AngularJS` (I have experienced before) but possible for others like `ReactJS or VueJS or even AngularJS 2` as well (so we could learn together). What do you think ?

**Comment by mrfeecler** [comment]
i think use angularJS 2 to everyone in our team learn more. ofcouse angularjs 1 it ok same. cause i bad too.

**Comment by tucq88** [comment]
AngularJS 2 is required : 
- Basic Javascript knowledge
- Typescript 
Highly recommend you guys take your time and read [these books](https://github.com/getify/You-Dont-Know-JS/) (Maybe first 3 books are enough)
Then we could proceed together later. Any suggestion on backend technologies ?
